version: "3"
services:
  web:
    image: nginx:alpine
    volumes:
      - ./var/www:/var/www
      - ./nginx/conf.d/flarum.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf.d/.nginx.conf:/etc/nginx/conf.d/.nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
    - 8015:80
    - 443:443
    networks:
      - code-network
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: flarum-fpm.dockerfile
    image: flup:latest
    volumes:
      - ./var/www:/var/www
    networks:
      - code-network
      - db-network
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=db_devblog
      - MYSQL_USER=devblog
      - MYSQL_PASSWORD=devbl0gp4ss
    volumes:
      - ../db/var/lib/mysql:/var/lib/mysql
    networks:
      - db-network

networks:
    code-network:
        driver: bridge
    db-network:
      driver: bridge

volumes:
  db:
